version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/template"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dotnet-10:
        patterns:
          - "Microsoft.*"
          - "Npgsql.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
